config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :boats, only: %i[index show update]

  root to: 'boats#index'
  get '/favorites', to: 'boats#favorites'
  get '/find_new_boats', to: 'boats#find_new_boats'
  get '/delete_old_boats', to: 'boats#delete_old_boats'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boat.rb
class Boat < ApplicationRecord
  has_paper_trail only: [:price]

  def price_history(prices = {}, boat = self)
    return price_history({ boat.updated_at => boat.price }) if prices.empty?

    older_boat = boat.paper_trail.previous_version
    return prices if older_boat.nil?

    price_history(prices.merge(older_boat.updated_at => older_boat.price), older_boat)
  end

  def listed?
    uri = URI(url)
    res = Net::HTTP.get_response(uri)
    return false unless res.code.to_i == 200

    html = Net::HTTP.get(uri)
    /The YachtWorld server has encountered an error/.match(html).nil?
  end

  OFFER_PERCENTAGE = 20
  def offer_price
    price.to_f - (price.to_f * (OFFER_PERCENTAGE / 100.0))
  end

  REGISTRATION_PRICE = 10
  def registration
    REGISTRATION_PRICE * length
  end

  TAX_PERCENTAGE = 7
  def taxes
    offer_price * (TAX_PERCENTAGE / 100.0)
  end

  INSURANCE_PERCENTAGE = 1.5
  def insurance
    offer_price * (INSURANCE_PERCENTAGE / 100.0)
  end

  def estimated_capital_expenditure
    offer_price + registration + taxes + insurance
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  before_action :set_boat, only: %i[show update]

  def index
    respond_to do |format|
      format.html
      format.json { render json: BoatDatatable.new(params, view_context: view_context) }
    end
  end

  def show; end

  def update
    respond_to do |format|
      if @boat.update(boat_params)
        format.html { redirect_to @boat, notice: 'Boat was successfully updated.' }
        format.json { render :show, status: :ok, location: @boat }
      else
        format.html { render :show }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  def favorites
    respond_to do |format|
      format.html
      format.json { render json: BoatDatatable.new(params, view_context: view_context, favorites: true) }
    end
  end

  def find_new_boats
    RetrieveBoatTraderBoatsJob.perform_later
    RetrieveYachtWorldBoatsJob.perform_later

    redirect_to :root, notice: 'Finding new boats...'
  end

  def delete_old_boats
    RemoveUnlistedYachtWorldBoatsJob.perform_later

    redirect_to :root, alert: 'Deleting old boats...'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_boat
    @boat = Boat.find(params[:id])
  end

  def boat_params
    params.require(:boat).permit(:yes, :no)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boats_helper.rb
module BoatsHelper
end

app/views/boats/favorites.html.erb
<%= javascript_pack_tag 'boats_table' %>

<div>
  Toggle column:
  <a class="toggle-vis" data-column="0" href="#">Description</a> -
  <a class="toggle-vis" data-column="1" href="#">Price</a> -
  <a class="toggle-vis" data-column="2" href="#">Length</a> -
  <a class="toggle-vis" data-column="3" href="#">Year</a> -
  <a class="toggle-vis" data-column="4" href="#">Location</a> -
  <a class="toggle-vis" data-column="5" href="#">URL</a> -
  <a class="toggle-vis" data-column="6" href="#">Last Updated</a>
</div>

<div data-turbolinks="false">
  <table id='boats' data-source="<%= favorites_path(format: :json) %>" class='table'>
    <thead>
      <tr>
        <th>Description</th>
        <th>Price</th>
        <th>Length</th>
        <th>Year</th>
        <th>Location</th>
        <th>URL</th>
        <th>Last Updated</th>
        <th class='hide_column'>Favorite</th>
        <th class='hide_column'>Nope!</th>
      </tr>
    </thead>
    <tbody>
    </tbody>
    <tfoot>
      <tr>
        <th>Description</th>
        <th>Price</th>
        <th>Length</th>
        <th>Year</th>
        <th>Location</th>
        <th>URL</th>
        <th>Last Updated</th>
        <th>Favorite</th>
        <th>Nope!</th>
      </tr>
    </tfoot>
  </table>
</div>

app/views/boats/index.html.erb
<%= javascript_pack_tag 'boats_table' %>

<% flash.each do |type, msg| %>
  <% alert_class = type == 'notice' ? 'alert-success' : 'alert-danger' %>
  <div class="alert alert-dismissible fade show <%= alert_class %>" role="alert">
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<div>
  <div class="form-group form-check">
    <input type="checkbox" name="showNo" class="form-check-input" id="showNo">
    <label class="form-check-label" for="showNo">Show hidden boats</label>
  </div>
</div>

<div data-turbolinks="false">
  <table id='boats' data-source="<%= boats_path(format: :json) %>" class='table'>
    <thead>
      <tr>
        <th>Description</th>
        <th>Price</th>
        <th>Length</th>
        <th>Year</th>
        <th>Location</th>
        <th>URL</th>
        <th>Last Updated</th>
        <th class='hide_column'>Favorite</th>
        <th class='hide_column'>Nope</th>
      </tr>
    </thead>
    <tbody>
    </tbody>
    <tfoot>
      <tr>
        <th>Description</th>
        <th>Price</th>
        <th>Length</th>
        <th>Year</th>
        <th>Location</th>
        <th>URL</th>
        <th>Last Updated</th>
        <th>Favorite</th>
        <th>Nope</th>
      </tr>
    </tfoot>
  </table>
</div>

app/views/boats/show.html.erb
<%= form_with model: @boat do |f| %>
  <div class="form-group form-check">
    <%= f.check_box 'yes', {class: 'form-check-input', onchange: 'this.form.submit()'} %>
    <%= f.label :yes, 'Add to Favorites', {class: 'form-check-label'} %>
  </div>
<% end %>

<%= form_with model: @boat do |f| %>
  <div class="form-group form-check">
    <%= f.check_box 'no', {class: 'form-check-input', onchange: 'this.form.submit()'} %>
    <%= f.label :no, 'Nope!', {class: 'form-check-label'} %>
  </div>
<% end %>

<h1><%= @boat.description %></h1>
<h2><%= @boat.length %> ft</h2>
<h3><%= @boat.year %></h3>
<h4><%= @boat.location %></h4>
<h5><%= link_to @boat.url, @boat.url, target: '_blank', rel: 'noreferrer' %></h5>
<h6>Last Updated: <%= time_tag @boat.updated_at %></h6>

<div class="card">
  <div class="card-header">Costs</div>
  <div class="card-body">
    <dl class="row">
      <dt class="col-sm-3">Price</dt>
      <dd class="col-sm-9"><%= number_to_currency @boat.price %></dd>
      <dt class="col-sm-3">Offer Price</dt>
      <dd class="col-sm-9"><%= number_to_currency @boat.offer_price %></dd>
      <dt class="col-sm-3">Registration</dt>
      <dd class="col-sm-9"><%= number_to_currency @boat.registration %></dd>
      <dt class="col-sm-3">Taxes</dt>
      <dd class="col-sm-9"><%= number_to_currency @boat.taxes %></dd>
      <dt class="col-sm-3">Insurance</dt>
      <dd class="col-sm-9"><%= number_to_currency @boat.insurance %></dd>
      <dt class="col-sm-3">Estimated Capital Expenditure</dt>
      <dd class="col-sm-9"><%= number_to_currency @boat.estimated_capital_expenditure %></dd>
    </dl>
  </div>
</div>

<% if @boat.versions.size > 0 %>
  <%= debug @boat.price_history %>
  <%= line_chart @boat.price_history %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Boats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container-fluid'>
      <nav class='navbar navbar-expand-md navbar-dark bg-dark fixed-top'>
        <a class='navbar-brand' href='/' data-turbolinks="false">
          <i class='fas fa-anchor'></i>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="/" data-turbolinks="false">Boats</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/favorites" tabindex="-1"  data-turbolinks="false">Favorites</a>
            </li>
          </ul>
          <div>
            <%= link_to 'Find New Boats', find_new_boats_path, class: 'btn btn-outline-success' %>
            <%= link_to 'Delete Old Boats', delete_old_boats_path, class: 'btn btn-outline-danger' %>
          </div>
        </div>
      </nav>
      <%= yield %>
    </div>
  </body>
</html>